import { StyleSheet } from 'react-native';

const globalStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#F1F8E9' }, // Light agricultural green instead of white
    containerCenter: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    splashTitle: { fontSize: 42, color: '#fff', fontWeight: 'bold', marginTop: 20 },
    splashTagline: { fontSize: 18, color: '#fff', opacity: 0.9 },
    headerTitle: { fontSize: 24, fontWeight: 'bold', color: '#2E7D32', textAlign: 'center', marginTop: 50, marginBottom: 30 },
    langList: { paddingHorizontal: 30 },
    langBtn: { backgroundColor: '#E8F5E9', padding: 20, borderRadius: 12, marginBottom: 15, alignItems: 'center', borderWidth: 1, borderColor: '#C8E6C9' },
    langText: { fontSize: 18, fontWeight: '600', color: '#1B5E20' },
    manualInput: { paddingHorizontal: 50, marginTop: 20 },
    input: { backgroundColor: '#F5F5F5', padding: 15, borderRadius: 10, borderWidth: 1, borderColor: '#DDD', marginBottom: 15, fontSize: 16 },
    brandName: { fontSize: 36, fontWeight: 'bold', color: '#2E7D32', textAlign: 'center', marginTop: 80 },
    card: { backgroundColor: '#fff', margin: 30, padding: 25, borderRadius: 20, elevation: 10, shadowColor: '#000', shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.2 },
    cardHeader: { fontSize: 22, fontWeight: '700', marginBottom: 20, color: '#333' },
    primaryBtn: { backgroundColor: '#2E7D32', padding: 16, borderRadius: 12, alignItems: 'center', marginVertical: 10 },
    btnText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
    map: { flex: 1 },
    locInfo: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: '#fff', padding: 20, borderTopLeftRadius: 20, borderTopRightRadius: 20, elevation: 20 },
    topBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16, borderBottomWidth: 1, borderBottomColor: '#eee' },
    homeTitle: { fontSize: 22, fontWeight: 'bold', color: '#2E7D32' },
    menuBox: { position: 'absolute', top: 60, left: 16, backgroundColor: '#fff', padding: 15, borderRadius: 10, elevation: 10, zIndex: 100, width: 250 },
    menuItem: { paddingVertical: 10, fontSize: 16, fontWeight: 'bold', color: '#333', borderBottomWidth: 1, borderBottomColor: '#eee' },
    menuItemRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12 },
    menuItemText: { marginLeft: 10, fontSize: 16, color: '#444' },
    scrollContent: { padding: 16 },
    grid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
    mainCard: { width: '48%', marginBottom: 16, borderRadius: 15, overflow: 'hidden', elevation: 5 },
    cardGradient: { padding: 20, height: 160, justifyContent: 'center', alignItems: 'center' },
    cardTitle: { color: '#fff', fontSize: 18, fontWeight: 'bold', marginTop: 10, textAlign: 'center' },
    cardDesc: { color: '#fff', fontSize: 12, opacity: 0.9, textAlign: 'center', marginTop: 5 },
    floatingChat: { position: 'absolute', bottom: 30, right: 30, backgroundColor: '#2E7D32', width: 65, height: 65, borderRadius: 33, justifyContent: 'center', alignItems: 'center', elevation: 10 },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
    chatContainer: { height: '80%', backgroundColor: '#fff', borderTopLeftRadius: 30, borderTopRightRadius: 30, overflow: 'hidden' },
    chatHeader: { flexDirection: 'row', justifyContent: 'space-between', padding: 20, backgroundColor: '#2E7D32', alignItems: 'center' },
    chatHeaderText: { color: '#fff', fontSize: 20, fontWeight: 'bold' },
    chatBody: { flex: 1, paddingHorizontal: 15 },
    msgBubble: { padding: 12, borderRadius: 15, marginVertical: 5, maxWidth: '80%' },
    msgUser: { alignSelf: 'flex-end', backgroundColor: '#E8F5E9' },
    msgAI: { alignSelf: 'flex-start', backgroundColor: '#F5F5F5' },
    msgText: { fontSize: 15 },
    msgTextUser: { color: '#1B5E20' },
    msgTextAI: { color: '#333' },
    chatInputArea: { flexDirection: 'row', padding: 15, borderTopWidth: 1, borderTopColor: '#eee', alignItems: 'center' },
    chatInput: { flex: 1, backgroundColor: '#F0F0F0', borderRadius: 25, paddingHorizontal: 20, height: 45, marginRight: 10 },
    sendBtn: { backgroundColor: '#2E7D32', width: 45, height: 45, borderRadius: 23, justifyContent: 'center', alignItems: 'center' },
    micBtn: { marginLeft: 10, backgroundColor: '#FF8F00', width: 45, height: 45, borderRadius: 23, justifyContent: 'center', alignItems: 'center' },
    pinnedBox: { backgroundColor: '#F1F8E9', borderLeftWidth: 4, borderLeftColor: '#2E7D32', padding: 15, borderRadius: 10, marginBottom: 15 },
    pinnedHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 5 },
    pinnedTitle: { flex: 1, marginLeft: 5, fontWeight: 'bold', color: '#2E7D32' },
    pinnedText: { fontSize: 14, color: '#333' },
    weatherHero: { padding: 40, alignItems: 'center', borderBottomLeftRadius: 40, borderBottomRightRadius: 40 },
    weatherDate: { color: '#fff', fontSize: 18 },
    weatherTemp: { color: '#fff', fontSize: 72, fontWeight: 'bold' },
    weatherStatus: { color: '#fff', fontSize: 24, marginBottom: 20 },
    weatherStats: { flexDirection: 'row', gap: 30 },
    statItem: { alignItems: 'center' },
    statVal: { color: '#fff', fontWeight: 'bold', fontSize: 18 },
    statLabel: { color: '#fff', fontSize: 12 },
    alertBox: { flexDirection: 'row', backgroundColor: '#FFEBEE', padding: 15, margin: 15, borderRadius: 12, alignItems: 'center' },
    alertText: { marginLeft: 10, color: '#B71C1C', fontWeight: '600', flex: 1 },
    sectionTitle: { fontSize: 20, fontWeight: 'bold', margin: 16, color: '#333' },
    forecastScroll: { paddingHorizontal: 16, marginBottom: 20 },
    forecastCard: { backgroundColor: '#fff', padding: 15, borderRadius: 15, alignItems: 'center', marginRight: 15, width: 80, elevation: 3 },
    forecastDay: { fontWeight: 'bold', marginBottom: 10 },
    forecastTemp: { marginTop: 10, fontWeight: 'bold' },
    p10: { padding: 10, flex: 1 },
    questionText: { fontSize: 22, fontWeight: 'bold', textAlign: 'center', marginBottom: 30, color: '#333' },
    cropItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#fff', padding: 20, borderRadius: 12, marginBottom: 10, elevation: 2 },
    cropName: { fontSize: 18, fontWeight: '600' },
    recCard: { backgroundColor: '#fff', padding: 20, borderRadius: 15, elevation: 3, marginBottom: 15 },
    recTitle: { fontSize: 20, fontWeight: 'bold', color: '#2E7D32', marginBottom: 5 },
    miniBtn: { backgroundColor: '#2E7D32', padding: 8, borderRadius: 8, alignSelf: 'flex-start', marginTop: 10 },
    miniBtnText: { color: '#fff', fontWeight: 'bold' },
    storageCard: { backgroundColor: '#fff', padding: 20, borderRadius: 15, elevation: 3, marginBottom: 15 },
    storageRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
    storageName: { fontSize: 18, fontWeight: 'bold', flex: 1 },
    statusBadge: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 10 },
    storageAddr: { color: '#666', marginBottom: 5 },
    callBtn: { flexDirection: 'row', backgroundColor: '#1976D2', padding: 12, borderRadius: 10, justifyContent: 'center', alignItems: 'center', marginTop: 15 },
    callText: { color: '#fff', fontWeight: '600', marginLeft: 10 },
    voiceControls: { marginTop: 30, alignItems: 'center' },
    langChoiceCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', padding: 20, marginHorizontal: 20, marginBottom: 15, borderRadius: 15, elevation: 3, borderWidth: 1, borderColor: '#eee' },
    selectedCard: { borderColor: '#2E7D32', backgroundColor: '#F1F8E9' },
    numberBadge: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#2E7D32', justifyContent: 'center', alignItems: 'center', marginRight: 15 },
    numberText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
    langChoiceText: { flex: 1, fontSize: 18, fontWeight: '600', color: '#333' },
    manualInputArea: { paddingHorizontal: 40, marginTop: 10 },
    keypadInput: { backgroundColor: '#fff', height: 60, borderRadius: 15, textAlign: 'center', fontSize: 24, fontWeight: 'bold', borderBottomWidth: 3, borderBottomColor: '#2E7D32' },
    actionArea: { marginTop: 30, alignItems: 'center', paddingHorizontal: 20 },
    stopActionBtn: { flexDirection: 'row', alignItems: 'center', padding: 12 },
    stopActionText: { marginLeft: 8, color: '#666', fontWeight: 'bold', fontSize: 16 },
    continueActionBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#2E7D32', paddingVertical: 18, paddingHorizontal: 50, borderRadius: 30, marginTop: 20, elevation: 5 },
    continueActionText: { color: '#fff', fontSize: 22, fontWeight: 'bold', marginRight: 10 },
    linkText: { color: '#2E7D32', textAlign: 'center', fontWeight: 'bold', fontSize: 16 },
    smallMapPreview: { height: 200, borderRadius: 20, overflow: 'hidden', marginBottom: 20, elevation: 5 },
    addressCard: { backgroundColor: '#fff', padding: 20, borderRadius: 20, elevation: 3 },
    addressRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 20 },
    addressLabel: { fontSize: 14, color: '#666', fontWeight: 'bold' },
    addressValue: { fontSize: 16, color: '#333', marginTop: 2 },
    coordGrid: { flexDirection: 'row', gap: 10, marginBottom: 20 },
    coordBox: { flex: 1, backgroundColor: '#F5F5F5', padding: 12, borderRadius: 12, alignItems: 'center' },
    coordLabel: { fontSize: 12, color: '#888' },
    coordValue: { fontSize: 14, fontWeight: 'bold', color: '#2E7D32' },
    addressGrid: { flexDirection: 'row', gap: 10, marginBottom: 15 },
    addressGridItem: { flex: 1, backgroundColor: '#FAF9F6', padding: 12, borderRadius: 12 },
});

export default globalStyles;
